### ISSUE TITLE
Failed to load on linux

### ISSUE THREAD

**Issue by jhessin** [Semantic-Org/Semantic-UI-CSS#42]
I am having an issue only on my Linux machine (my other machine is a mac). When attempting to but when attempting to build the application on my Linux machine I get this error:

```
ERROR in ./node_modules/semantic-ui-css/themes/default/assets/images/flags.png
Module build failed: Error: /home/jhessin/websites/database/node_modules/pngquant-bin/vendor/pngquant: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

    at Promise.all.then.arr (/home/jhessin/websites/database/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

 @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/semantic-ui-css/semantic.min.css 7:116229-116280
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.coffee
```

Here is my webpack.config.coffee modules and resolve settings:
```coffeescript
module: rules: [
    {
      test: /\.(gif|png|jpe?g|svg)$/i
      use: [
        'file-loader'
        loader: 'image-webpack-loader'
        options:
          bypassOnDebug: true
      ]
    }
    {
      test: /\.(sass|scss|css)$/
      use:[
        { loader: 'style-loader' }
        { loader: 'css-loader' }
        { loader: 'sass-loader' }
      ]
    }
    {
      test: /\.(woff|woff2|eot|ttf|otf)$/,
      loader: 'file-loader'
    }
    {
      test: /\.(coffee|cson)$/
      use:[
        loader: 'coffee-loader'
        options:
          transpile:
            presets: ['env']
      ]
    }
  ]
  resolve:
    extensions: [
      '.js', '.json'
      '.coffee', '.cson', '.sass', '.scss'
    ]
```

yarn: v1.3.2
webpack: v3.11.0
node: v9.5.0
npm: 5.6.0

**Comment by jhessin** [comment]
I found a workaround [here](
https://github.com/tcoopman/image-webpack-loader/issues/95
):

```bash
wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
  && sudo dpkg -i /tmp/libpng12.deb \
  && rm /tmp/libpng12.deb
```
